version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-home-v6-{{ checksum "build.gradle" }}
            - gradle-home-v6
      - run: ./gradlew build
      - store_test_results:
          path: build/test-results
      - run: ./gradlew documentation traceRequirements docZip
      - run: ./gradlew uploadCoverage
      - when:
          condition: << CIRCLE_PR_NUMBER >>
          steps:
            - run: ./gradlew sonarqube -Dsonar.login=$SONAR_LOGIN -Dsonar.pullrequest.key=$CIRCLE_PR_NUMBER -Dsonar.pullrequest.branch=$CIRCLE_BRANCH
      - unless:
          condition: << CIRCLE_PR_NUMBER >>
          steps:
            - run: ./gradlew sonarqube -Dsonar.login=$SONAR_LOGIN -Dsonar.branch.name=$CIRCLE_BRANCH
      - save_cache:
          key: gradle-home-v6-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle
      - store_artifacts:
          path: build/docs
      - store_artifacts:
          path: build/reports/tracing.html
      - store_artifacts:
          path: build/distributions