version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run: ./gradlew build
      - store_test_results:
          path: build/test-results