version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-home-v1-{{ checksum "build.gradle" }}
            - gradle-home-v1
      - run: ./gradlew --no-daemon build
      - save_cache:
          key: gradle-home-v1-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle
      - store_test_results:
          path: build/test-results

  convert:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run: ./gradlew --no-daemon asciidoctor
      - store_artifacts:
          path: build/asciidoc

workflows:
  version: 2
  build-convert:
    jobs:
      - build
      - convert:
          requires:
            - build