version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-home-v2-{{ checksum "build.gradle" }}
            - gradle-home-v2
      - run: ./gradlew --no-daemon build
      - store_test_results:
          path: build/test-results
      - run: ./gradlew --no-daemon asciidoctor traceRequirements
      - save_cache:
          key: gradle-home-v2-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle
      - store_artifacts:
          path: build/docs
      - store_artifacts:
          path: build/reports/tracing.html
