= AdocSpec Design
Axel von Engel <a.vonengel@gmail.com>
2019-01-31
:revnumber: {project-version}
ifndef::imagesdir[:imagesdir: images]
ifndef::sourcedir[:sourcedir: ../java]
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

This is the design document for the AdocSpec project. It describes the software design that implements the requirements
found in <<spec#,the specification>> in detail.

== Exploration

.TreeProcessor
The initial approach was to write a combination of AsciiDoctor `extensions`, mainly a TreeProcessor. This looked
promising at first, but soon led to the following problem: To export a specification item's text fields, the content
of the AsciiDoctor AST nodes needs to be accessed by the TreeProcessor. However, this does not seem to be supported
by AsciiDoctor's extension model. A `TreeProcessor` has the ability to traverse the block level content of the document,
but does not get AST access to e.g. paragraph content. This leaves the following options to access paragraph content:

AsciiDoc source::
It is possible to retrieve the source in AsciiDoc format. This would leave AsciiDoc markup in the specification item
content, which would be acceptable. However, other inline content will also be unprocessed. The main issue are references
to AsciiDoc variables.
Content::
It is also possible to retrieve the '`content`' of a block. This will _convert_ the paragraph content to the current
output format, though. Converting to HTML means the specification item content would contain HTML tags, while converting
to DocBook results in DocBook tags, and so on.
Convert::
The last option is to convert the whole block. This results in the same output as if the '`content`' was accessed, plus
encompassing tags, depending on the type of block.

.Converter
The alternative approach that is currently being explored is to write an AsciiDoc Converter to generate ReqM XML output.
This converter implementation is then called by AsciiDoctor for each element in the AST of the document - this time
including sub-paragraph level items.

== Converter Design

This section describes the software design related to the implementation of an `org.asciidoctor.converter.Converter`
that extends AsciiDoctorJ to provide the ability to generate OFT specification item XML output for an AsciiDoc document.

`+dsn~oft-equivalent.id~1+`

The `SpecificationConverter` accepts any paragraph as a specification item's ID, if the text content evaluates to something
that matches the pattern described in the OFT specification (which is reiterated in `+req~oft-equivalent.id~1+` for
convenience).

NOTE: In contrast to Markdown, it is not enough to enclose the ID in backticks (```). This will only cause the enclosed
text to be set in `monospace`. With the OFT ID format containing tilde symbols, this leads to the actual ID part to be
set in subscript (e.g. `dsn~oft-equivalent.id~1`). In order for this to render correctly, use
link:https://asciidoctor.org/docs/user-manual/#literal-monospace[literal monospace]: `pass:[`+]` and `pass:[+`]`,
e.g. `pass:[`+dsn~oft-equivalent.id~1+`]`.

Needs: impl, test

Covers:

* +req~oft-equivalent.id~1+

---

The remainder of this section lists forwarding specification items that do not require further design

dsn -> impl, test: +req~oft-equivalent.description~1+

dsn -> impl, test: +req~oft-equivalent.needs~1+

dsn -> impl, test: +req~oft-equivalent.covers~1+

dsn -> impl, test: +req~oft-equivalent.status~1+

dsn -> impl, test: +req~oft-equivalent.rationale~1+

dsn -> impl, test: +req~oft-equivalent.forwarding_needed_coverage~1+

dsn -> impl, test: +req~oft-equivalent.specification-item-title~1+