= AdocSpec Specification
Axel von Engel <a.vonengel@gmail.com>
2018-12-27
:revnumber: {project-version}
ifndef::imagesdir[:imagesdir: images]
ifndef::sourcedir[:sourcedir: ../java]

This is the specification for the adocspec project.

== Introduction

`+goal~adocspec-goal~1+`

The adocspec project aims at making writing requirements in AsciiDoc format
possible by using the openfasttrace tracing toolchain.

Needs: feat

== Features

`+feat~oft-equivalent~1+`

AdocSpec provides an equivalent syntax for specifying requirements in AsciiDoc, as OFT does natively for Markdown.

Rationale: The OFT syntax is simple and easy to use. Also, users migrating their requirements documents from Markdown
to AsciiDoc will have to make less changes.

Needs: req

Covers:

* +goal~adocspec-goal~1+

== Supported AsciiDoc Format

The AdocSpec extension for AsciiDoctor supports a variety of AsciiDoc elements to specify requirements. The details are
explained in the following sections.

=== OFT Equivalent Format

As described in <<feat~adocspec-oft-equivalent>>, AdocSpec supports an equivalent of OFT's Markdown syntax in AsciiDoc.
This section lists the detailed syntax requirements.

`+req~oft-equivalent.id~1+`

A requirement may be defined by simply adding a paragraph that only contains a specification item ID in OFT syntax:
....
requirement-id = type "~" id "~" revision

type = 1*ALPHA

id = id-fragment *("." id-fragment)

id-fragment = ALPHA *(ALPHA / DIGIT / "_" / "-")

revision = 1*DIGIT
....

Needs: dsn

Covers:

* +feat~oft-equivalent~1+