= AdocSpec Specification
Axel von Engel <a.vonengel@gmail.com>
2018-12-27
:revnumber: {project-version}
ifndef::imagesdir[:imagesdir: images]
ifndef::sourcedir[:sourcedir: ../java]
:oft-design: https://github.com/itsallcode/openfasttrace/blob/develop/doc/design.md
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

This is the specification for the adocspec project.

== Introduction

`+goal~adocspec-goal~1+`

The adocspec project aims at making writing requirements in AsciiDoc format
possible by using the openfasttrace tracing toolchain.

Needs: feat

== Features

`+feat~oft-equivalent~1+`

AdocSpec provides an equivalent syntax for specifying requirements in AsciiDoc, as OFT does natively for Markdown.

Rationale: The OFT syntax is simple and easy to use. Also, users migrating their requirements documents from Markdown
to AsciiDoc will have to make less changes.

Needs: req

Covers:

* +goal~adocspec-goal~1+


****
The OFT Gradle plugin currently does not support exclusion of "`draft`" items, therefore the
following spec is disabled.
****

----
`+feat~oft-asciidoc-extension~1+`

Status: draft

AdocSpec extends the OFT equivalent syntax with elements from AsciiDoc.

Rationale: Some elements of AsciiDoc integrate easily with the OFT syntax. The best example are AsciiDoc captions:
they can easily be used to declare a paragraph as description, rationale, or comment.

Needs: req

Covers:

* +goal~adocspec-goal~1+
----

== Supported AsciiDoc Format

The AdocSpec extension for AsciiDoctor supports a variety of AsciiDoc elements to specify requirements. The details are
explained in the following sections.

=== OFT Equivalent Format

As described in <<feat~adocspec-oft-equivalent>>, AdocSpec supports an equivalent of OFT's Markdown syntax in AsciiDoc.
This section lists the detailed syntax requirements.

.Specification Item ID
`+req~oft-equivalent.id~1+`

A requirement definition may be started by a paragraph that only contains a specification item ID in OFT syntax (compare
{oft-design}#markdown-specification-item-id-format[`+dsn~md.specification-item-id-format~2+`]):
....
requirement-id = type "~" id "~" revision

type = 1*ALPHA

id = id-fragment *("." id-fragment)

id-fragment = ALPHA *(ALPHA / DIGIT / "_" / "-")

revision = 1*DIGIT
....

Needs: dsn

Covers:

* +feat~oft-equivalent~1+

.Description
`+req~oft-equivalent.description~1+`

Any paragraph inside a specification item that has no special meaning attached via keywords, is added to the
description of the item.

Needs: dsn

Covers:

* +feat~oft-equivalent~1+

.Rationale
`+req~oft-equivalent.rationale~1+`

Any paragraph following the keyword "`Rationale:`" is appended to the rationale of the specification
item.

Needs: dsn

Covers:

* +feat~oft-equivalent~1+

.Comment
`+req~oft-equivalent.comment~1+`

Any paragraph following the keyword "`Comment:`" is appended to the comment of the specification
item.

Needs: dsn

Covers:

* +feat~oft-equivalent~1+

.Needs
`+req~oft-equivalent.needs~1+`

The needed coverage types are specified in AsciiDoc just like in Markdown. The keyword "`Needs:`" is
placed before a list of specification item types that are needed to fully cover the current
specification item. Compare
{oft-design}#markdown-needs-list[`+dsn~md.needs-coverage-list~2+`]:

....
needs-list = "Needs:" *WSP reference *("," *WSP reference)
....

Needs: dsn

Covers:

* +feat~oft-equivalent~1+

.Covers
`+req~oft-equivalent.covers~1+`

The covered artifact IDs are specified in AsciiDoc just like in Markdown. Compare
{oft-design}#markdown-covers-list[`+dsn~md.covers-list~1+`]:

....
covers-list = covers-header 1*(LINEBREAK covers-line)

covers-header = "Covers:" *WSP

covers-line = *WSP "*" *WSP reference
....

Only one traced reference per line is supported. Any optional text after the reference is
ignored if it is separated by at least one whitespace character.

Needs: dsn

Covers:

* +feat~oft-equivalent~1+

.Status
`+req~oft-equivalent.status~1+`

The status field of specification item may be set as follows:

....
status = "Status:" *WSP ("approved" / "proposed" / "draft")
....

Needs: dsn

Covers:

* +feat~oft-equivalent~1+

.Forwarding Needed Coverage
`+req~oft-equivalent.forwarding_needed_coverage~1+`

AdocSpec supports forwarding required coverage from one artifact type to one or more different artifact types using the
following notation.

....
artifact-need-redirection = skipped-artifact-type *WSP "->" *WSP target-artifact-list
    *WSP ":" *WSP original-requirement-id

skipped-artifact-type = artifact-type

target-artifact-list = artifact-type *("," *WSP artifact-type)

original-requirement-id = requirement-id....
....

The following example shows an architectural specification item that forwards the needed coverage directly to the
detailed design and an integration test.

....
arch -> dsn, itest : req~skip-this-requirement~1
....

NOTE: In contrast to OFT's Markdown format, AdocSpec uses a right arrow with a *single* dash, as this is nicely converted
in HTML/DocBook: ->

Needs: dsn

Covers:

* +feat~oft-equivalent~1+

.Specification Item Title
`+req~oft-equivalent.specification-item-title~1+`

If an AsciiDoc _section_ title directly precedes a specification item ID, then the AsciiDoc title is used as title for the specification item.

Rationale:

AsciiDoc titles show up in the outline and are a natural way of defining a requirement title.

Comment:

In AsciiDoc individual blocks may have titles, too. This has no Markdown equivalent, however.

Needs: dsn

Covers:

* +feat~oft-equivalent~1+


== OFT AsciiDoc Extensions

This section contains ideas for some extensions of the OFT syntax with AsciiDoc elements.

=== Captions

AsciiDoc captions can easily be used to replace the "`Description:`", "`Rationale:`", or "`Comment:`" prefixes.

Examples:
....
.Description
A specification item's description may be defined by using the caption "`Description`".

.Rationale
A specification item's rationale may be defined by using the caption "`Rationale`".

.Comment
A specification item's comment may be defined by using the caption "`Comment`".
....

renders as:
====
.Description
A specification item's description may be defined by using the caption "`Description`".

.Rationale
A specification item's rationale may be defined by using the caption "`Rationale`".

.Comment
A specification item's comment may be defined by using the caption "`Comment`".
====

=== Roles

AsciiDoc allows to define roles for a paragraph. This could also be used to declare if a paragraph should be used for
description, rationale, or comment. However, just assigning a role does not change the conversion to the presentation format.
This means the output format converter needs some additional configuration to make the roles change the presentation.

On the other hand, some people might prefer to just declare these distinctions for the tracing toolchain, and present
the content in the presentation format without any visible clues as to which is what, and let the reader determine it
from the content itself.

=== Block Macros

AsciiDoc also allows extensions to define their own block macros. This could be used in various ways:

Specification Item end marker::
There is no end marker for a specificaiton item in OFT. Instead, a specification item ends when the section ends,
or another specification item starts via a its ID. It is impossible to add a paragraph to the informative
content _after_ a specification item, but _inside_ the same section.

Replacement for Needs/Covers/ID::
A block macro could be used to define the needed coverage types, covered specification item IDs, or the ID of the
specification item. This does not really add much value to the source document, but could be rendered to the
presentation format into a more complex structure, for example by using a template.
+
At Elektrobit, we have an XSL stylesheet to transform specification items in XML format to DocBook table.

=== Link Anchors

It would be really easy and useful if links could reference a requirement by ID. For this purpose, link anchors could be
added, probably through a https://asciidoctor.org/docs/user-manual/#extension-points[TreeProcessor].

